version: '3.4'

services:
  jaeger:
    build: 
      context: ./jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 
    privileged: true
    # command: sleep infinity 
    restart: always
    ports: 
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks: 
      - app_net

networks:
    app_net:
        external: true