version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant"
    volumes:
      - /home/ubuntu/homeassistant/config:/config
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    networks:
      - app_net


networks:
    app_net:
        external: true
