version: '3.4'

services:
  ts:
    build: 
      context: ./ts
    privileged: true
    command: sleep infinity 
    volumes:
      - "ts-data:/workspace"
    restart: always
    networks: 
      - app_net

networks:
    app_net:
        external: true

volumes:
  ts-data: