version: '3.4'

services:
  strongswan-sun:
    build: 
      context: ./strongswan
    privileged: true
    command: sleep infinity 
    restart: always
    networks: 
      - app_net

  strongswan-moon:
    build: 
      context: ./strongswan
    privileged: true
    command: sleep infinity 
    restart: always
    networks: 
      - app_net

networks:
    app_net:
        external: true